steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/talk-to-celebrity-backend:$SHORT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/talk-to-celebrity-backend:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "talk-to-celebrity-backend",
        "--image=gcr.io/$PROJECT_ID/talk-to-celebrity-backend:$SHORT_SHA",
        "--region=us-central1",
        "--allow-unauthenticated",
        "--set-secrets",
        "MONGO_DB_URI=apollo-hms-db-uri:latest,FIREBASE_SERVICE_ACCOUNT=apollo-hms-service-account:latest,POSTMARK_ACCOUNT_TOKEN=apollo-hms-postmark-api-key:latest,POSTMARK_SERVER_TOKEN= apollo-postmark-server-token:latest,SMS_API_KEY=sms-api-key:latest,SMS_SENDER_ID=sms-sender-id:latest",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
